export const fetchProducts = async () => {
  const products = [
    {
      id: 1,
      imageUrl: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
      name: "Nike Air Monarch IV",
      price: "200",
      company: "Nike",
      category: "sneakers",
      rating: "5",
    },
    {
      id: 2,
      imageUrl: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
      name: "Nike Air Vapormax Plus",
      price: "$140,00",
      company: "Nike",
      category: "sneakers",
      rating: "2",
    },
    {
      id: 3,
      imageUrl: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
      name: "Nike Waffle One Sneaker",
      price: "$140,00",
      company: "Nike",
      category: "sneakers",
      rating: "4",
    },
    {
      id: 4,
      imageUrl: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
      name: "Nike Running Shoe",
      price: "$140,00",
      company: "Adidas",
      category: "sneakers",
      rating: "3",
    },
    {
      id: 5,
      imageUrl: "https://m.media-amazon.com/images/I/41M54ztS6IL._AC_SY625._SX._UX._SY._UY_.jpg",
      name: "Flat Slip On Pumps",
      price: "$140,00",
      company: "Vans",
      category: "flats",
      rating: "1",
    },
    {
      id: 6,
      imageUrl: "https://m.media-amazon.com/images/I/71zKuNICJAL._AC_UX625_.jpg",
      name: "Knit Ballet Flat",
      price: "140",
      company: "Adidas",
      category: "flats",
      rating: "3",
    },
    {
      id: 7,
      imageUrl: "https://m.media-amazon.com/images/I/61V9APfz97L._AC_UY695_.jpg",
      name: "Loafer Flats",
      price: "90",
      company: "Vans",
      category: "flats",
      rating: "3",
    },
    {
      id: 8,
      imageUrl: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
      name: "Nike Zoom Freak",
      price: "85",
      company: "Nike",
      category: "sneakers",
      rating: "4",
    },
    {
      id: 9,
      imageUrl: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
      name: "Nike Men's Sneaker",
      price: "55",
      company: "Adidas",
      category: "sneakers",
      rating: "5",
    },
    {
      id: 10,
      imageUrl: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
      name: "PUMA BLACK-OCE",
      price: "90",
      company: "Puma",
      category: "sneakers",
      rating: "2",
    },
    {
      id: 11,
      imageUrl: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
      name: "Pacer Future Sneaker",
      price: "120",
      company: "Puma",
      category: "sneakers",
      rating: "2",
    },
    {
      id: 12,
      imageUrl: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
      name: "Unisex-Adult Super",
      price: "70",
      company: "Puma",
      category: "sneakers",
      rating: "3",
    },
    {
      id: 13,
      imageUrl: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
      name: "Roma Basic Sneaker",
      price: "30",
      company: "Puma",
      category: "sneakers",
      rating: "1",
    },
    {
      id: 14,
      imageUrl: "https://m.media-amazon.com/images/I/7128-af7joL._AC_UY575_.jpg",
      name: "Pacer Future Doubleknit",
      price: "160",
      company: "Puma",
      category: "sneakers",
      rating: "2",
    },
    {
      id: 15,
      imageUrl: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
      name: "Fusion Evo Golf Shoe",
      price: "150",
      company: "Puma",
      category: "sneakers",
      rating: "5",
    },
    {
      id: 16,
      imageUrl: "https://m.media-amazon.com/images/I/719gdz8lsTS._AC_UX575_.jpg",
      name: "Rainbow Chex Skate",
      price: "130",
      company: "Vans",
      category: "flats",
      rating: "4",
    },
    {
      id: 17,
      imageUrl: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
      name: "Low-Top Trainers",
      price: "40",
      company: "Vans",
      category: "sandals",
      rating: "2",
    },
    {
      id: 18,
      imageUrl: "https://m.media-amazon.com/images/I/71pf7VFs9CL._AC_UX575_.jpg",
      name: "Vans Unisex Low-Top",
      price: "22",
      company: "Vans",
      category: "sandals",
      rating: "3",
    },
    {
      id: 19,
      imageUrl: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
      name: "Classic Bandana Sneakers",
      price: "60",
      company: "Nike",
      category: "sandals",
      rating: "1",
    },
    {
      id: 20,
      imageUrl: "https://m.media-amazon.com/images/I/61bncQ44yML._AC_UX695_.jpg",
      name: "Chunky High Heel",
      price: "210",
      company: "Vans",
      category: "heels",
      rating: "3",
    },
    {
      id: 21,
      imageUrl: "https://m.media-amazon.com/images/I/71czu7WgGuL._AC_UY695_.jpg",
      name: "Slip On Stiletto High Heel",
      price: "14",
      company: "Puma",
      category: "heels",
      rating: "5",
    },
    {
      id: 22,
      imageUrl: "https://m.media-amazon.com/images/I/61men05KRxL._AC_UY625_.jpg",
      name: "DREAM PAIRS Court Shoes",
      price: "40",
      company: "Nike",
      category: "heels",
      rating: "5",
    },
    {
      id: 23,
      imageUrl: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
      name: "Nike Air Vapormax Plus",
      price: "99",
      company: "Nike",
      category: "sneakers",
      rating: "4",
    },
    {
      id: 24,
      imageUrl: "https://m.media-amazon.com/images/I/51PGWTXgf-L._AC_UY625_.jpg",
      name: "Low Mid Block Heels",
      price: "110",
      company: "Nike",
      category: "heels",
      rating: "2",
    },
    {
      id: 25,
      imageUrl: "https://m.media-amazon.com/images/I/616sA5XUKtL._AC_UY675_.jpg",
      name: "Chunky High Heel",
      price: "140",
      company: "Adidas",
      category: "heels",
      rating: "4",
    },
    {
      id: 26,
      imageUrl: "https://m.media-amazon.com/images/I/71h5+MbEK7L._AC_UY625_.jpg",
      name: "Amore Fashion Stilettos",
      price: "140",
      company: "Adidas",
      category: "heels",
      rating: "3",
    },
    {
      id: 27,
      imageUrl: "https://m.media-amazon.com/images/I/61uw5RDxKQL._AC_UY625_.jpg",
      name: "Bridal Sandals Glitter",
      price: "140",
      company: "Adidas",
      category: "heels",
      rating: "4",
    },
    {
      id: 28,
      imageUrl: "https://m.media-amazon.com/images/I/71yhoZP0l6L._AC_UY695_.jpg",
      name: "Wedding Prom Bridal",
      price: "140",
      company: "Adidas",
      category: "flats",
      rating: "4",
    },
  ];

  return {
    data: products
  };
};
